import { gql, useQuery } from '@apollo/client';

const STATS = gql`query AdminOperationalStats { adminDashboardStats { openModerationCases pendingVerifications overdueVerifications resolvedModerationLast7Days verificationDecisionsLast7Days } }`;
type Stats = { adminDashboardStats: { openModerationCases: number; pendingVerifications: number; overdueVerifications: number; resolvedModerationLast7Days: number; verificationDecisionsLast7Days: number } };

export default function AnalyticsPage() {
  const { data, loading, error, refetch } = useQuery<Stats>(STATS, { pollInterval: 60_000 }); const stats = data?.adminDashboardStats;
  const cards = stats ? [{ title: 'Open moderation', value: stats.openModerationCases, detail: 'Cases requiring action' }, { title: 'Pending verification', value: stats.pendingVerifications, detail: 'Organisation submissions' }, { title: 'Overdue verification', value: stats.overdueVerifications, detail: 'Past the three-day SLA' }, { title: 'Moderation resolved', value: stats.resolvedModerationLast7Days, detail: 'Last seven days' }, { title: 'Verification decisions', value: stats.verificationDecisionsLast7Days, detail: 'Last seven days' }] : [];
  return <div className="mx-auto max-w-[1440px]"><div className="flex items-end justify-between border-b border-[#DFE1E6] pb-5"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-slate-500">Operations</p><h2 className="mt-1 text-2xl font-semibold">Platform activity</h2><p className="mt-1 text-sm text-slate-600">Live queue depth, SLA pressure, and recent throughput.</p></div><button onClick={() => void refetch()} className="h-9 rounded border bg-white px-3 text-sm font-semibold">Refresh</button></div>{loading ? <p className="p-16 text-center text-sm text-slate-500">Loading operational data…</p> : error ? <p className="mt-5 rounded border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error.message}</p> : <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map((card) => <article key={card.title} className="rounded-lg border bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{card.title}</p><p className="mt-3 text-3xl font-semibold">{card.value}</p><p className="mt-2 text-xs text-slate-500">{card.detail}</p></article>)}</div>}</div>;
}
