import { gql, useMutation, useQuery } from '@apollo/client';
import { useState } from 'react';
import { formatDate, StatusBadge } from './moderation/ModerationQueuePage';

const QUERY = gql`query EmailDeliveries($status: EmailDeliveryStatus, $search: String, $after: String) { emailDeliveries(status: $status, search: $search, after: $after, limit: 25) { edges { id templateKey to subject status provider providerMessageId error attemptCount sourceService sourceEntityType sourceEntityId queuedAt sentAt createdAt events { event occurredAt response } } hasNextPage endCursor } }`;
const RETRY = gql`mutation RetryEmailDelivery($id: ID!) { retryEmailDelivery(id: $id) { id status attemptCount queuedAt error } }`;

type Delivery = { id: string; templateKey: string; to: string; subject: string; status: string; provider: string; providerMessageId: string | null; error: string | null; attemptCount: number; sourceService: string | null; sourceEntityType: string | null; sourceEntityId: string | null; queuedAt: string | null; sentAt: string | null; createdAt: string; events: Array<{ event: string; occurredAt: string; response: string | null }> };

export default function EmailDeliveriesPage() {
  const [status, setStatus] = useState('');
  const [search, setSearch] = useState('');
  const [selected, setSelected] = useState<Delivery | null>(null);
  const { data, loading, error, refetch, fetchMore } = useQuery<{ emailDeliveries: { edges: Delivery[]; hasNextPage: boolean; endCursor: string | null } }>(QUERY, { variables: { status: status || null, search: search.trim() || null }, fetchPolicy: 'network-only' });
  const [retry, { loading: retrying }] = useMutation(RETRY, { onCompleted: () => void refetch() });
  const connection = data?.emailDeliveries;
  return <div className="mx-auto max-w-[1400px]">
    <div className="flex flex-wrap items-end justify-between gap-4 border-b pb-5"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-slate-500">Messaging operations</p><h2 className="mt-1 text-2xl font-semibold">Email delivery</h2><p className="mt-1 text-sm text-slate-600">Transactional messages, provider outcomes, and controlled retries.</p></div><button onClick={() => void refetch()} className="h-9 rounded border bg-white px-3 text-sm font-semibold">Refresh</button></div>
    <div className="mt-5 flex flex-wrap gap-3 rounded-lg border bg-white p-4"><input aria-label="Search email deliveries" value={search} onChange={(event) => setSearch(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && void refetch()} placeholder="Recipient, subject, or message ID" className="h-9 min-w-[280px] flex-1 rounded border px-3 text-sm" /><select aria-label="Delivery status" value={status} onChange={(event) => setStatus(event.target.value)} className="h-9 rounded border bg-white px-3 text-sm"><option value="">All statuses</option>{['QUEUED', 'ACCEPTED', 'SENT', 'FAILED', 'SUPPRESSED'].map((value) => <option key={value}>{value}</option>)}</select></div>
    {loading && !connection ? <State text="Loading email deliveries…" /> : error ? <State text="Email delivery history could not be loaded." /> : !connection?.edges.length ? <State text="No email deliveries match these filters." /> : <section className="mt-5 overflow-x-auto rounded-lg border bg-white"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-[#F7F8FA] text-[11px] uppercase text-slate-500"><tr><th className="px-4 py-3">Created</th><th className="px-4 py-3">Recipient</th><th className="px-4 py-3">Template</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Attempts</th><th className="px-4 py-3">Actions</th></tr></thead><tbody className="divide-y">{connection.edges.map((item) => <tr key={item.id}><td className="whitespace-nowrap px-4 py-3 text-xs text-slate-500">{formatDate(item.createdAt)}</td><td className="px-4 py-3"><p className="font-semibold">{item.to}</p><p className="mt-1 max-w-[360px] truncate text-xs text-slate-500">{item.subject}</p></td><td className="px-4 py-3 font-mono text-xs">{label(item.templateKey)}</td><td className="px-4 py-3"><StatusBadge value={item.status} /></td><td className="px-4 py-3">{item.attemptCount}</td><td className="px-4 py-3"><button onClick={() => setSelected(item)} className="mr-3 text-sm font-semibold text-blue-700">Inspect</button>{item.status === 'FAILED' && <button disabled={retrying} onClick={() => void retry({ variables: { id: item.id } })} className="text-sm font-semibold text-blue-700 disabled:opacity-50">Retry</button>}</td></tr>)}</tbody></table>{connection.hasNextPage && <div className="border-t p-4 text-center"><button onClick={() => void fetchMore({ variables: { after: connection.endCursor }, updateQuery: (previous, { fetchMoreResult }) => ({ emailDeliveries: { ...fetchMoreResult.emailDeliveries, edges: [...previous.emailDeliveries.edges, ...fetchMoreResult.emailDeliveries.edges] } }) })} className="rounded border px-4 py-2 text-sm font-semibold">Load more</button></div>}</section>}
    {selected && <div role="dialog" aria-modal="true" aria-label="Email delivery details" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4" onMouseDown={(event) => event.target === event.currentTarget && setSelected(null)}><div className="max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-lg bg-white shadow-xl"><div className="flex items-start justify-between border-b p-5"><div><h3 className="text-lg font-semibold">{selected.subject}</h3><p className="mt-1 text-sm text-slate-500">{selected.to}</p></div><button onClick={() => setSelected(null)} aria-label="Close" className="rounded p-2 text-slate-500">×</button></div><dl className="grid gap-px bg-slate-200 sm:grid-cols-2">{[['Template', label(selected.templateKey)], ['Status', selected.status], ['Provider message ID', selected.providerMessageId ?? '—'], ['Source', [selected.sourceService, selected.sourceEntityType, selected.sourceEntityId].filter(Boolean).join(' / ') || '—']].map(([name, value]) => <div key={name} className="bg-white p-4"><dt className="text-[11px] font-semibold uppercase text-slate-500">{name}</dt><dd className="mt-1 break-all text-sm">{value}</dd></div>)}</dl>{selected.error && <div className="m-5 rounded border border-red-200 bg-red-50 p-4 text-sm text-red-800">{selected.error}</div>}<div className="p-5"><h4 className="text-sm font-semibold">Provider events</h4>{selected.events.length ? <div className="mt-3 divide-y rounded border">{selected.events.map((item, index) => <div key={`${item.event}-${index}`} className="p-3"><div className="flex justify-between gap-3"><span className="font-semibold">{label(item.event)}</span><span className="text-xs text-slate-500">{formatDate(item.occurredAt)}</span></div>{item.response && <p className="mt-1 text-xs text-slate-600">{item.response}</p>}</div>)}</div> : <p className="mt-2 text-sm text-slate-500">No provider webhook events recorded yet.</p>}</div></div></div>}
  </div>;
}

function State({ text }: { text: string }) { return <p className="mt-5 rounded-lg border bg-white p-14 text-center text-sm text-slate-500">{text}</p>; }
function label(value: string) { return value.replace(/_/g, ' ').toLowerCase().replace(/(^|\s)\S/g, (char) => char.toUpperCase()); }
