import { gql, useQuery } from '@apollo/client';
import { formatDate, StatusBadge } from './moderation/ModerationQueuePage';

const QUERY = gql`query AdminSystemHealth { adminSystemHealth { overallStatus version checkedAt dependencies { name category status detail latencyMs checkedAt } } }`;
type Health = { overallStatus: string; version: string; checkedAt: string; dependencies: Array<{ name: string; category: string; status: string; detail: string; latencyMs: number | null; checkedAt: string }> };
export default function SystemHealthPage() {
  const { data, loading, error, refetch } = useQuery<{ adminSystemHealth: Health }>(QUERY, { pollInterval: 60_000, fetchPolicy: 'network-only' }); const health = data?.adminSystemHealth;
  return <div className="mx-auto max-w-[1200px]"><div className="flex flex-wrap items-end justify-between gap-3 border-b pb-5"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-slate-500">Read-only diagnostics</p><h2 className="mt-1 text-2xl font-semibold">System health</h2><p className="mt-1 text-sm text-slate-600">Live subgraph health and configuration readiness. No secrets are exposed.</p></div><button onClick={() => void refetch()} className="h-9 rounded border bg-white px-3 text-sm font-semibold">Run checks</button></div>{loading && !health ? <State text="Checking dependencies…" /> : error ? <State text={error.message} /> : health && <><div className="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-lg border bg-white p-5"><div><p className="text-xs font-semibold uppercase text-slate-500">Overall status</p><div className="mt-2"><StatusBadge value={health.overallStatus} /></div></div><div className="text-right text-xs text-slate-500"><p>Version: <span className="font-mono text-slate-700">{health.version}</span></p><p className="mt-1">Checked {formatDate(health.checkedAt)}</p></div></div><section className="mt-5 overflow-hidden rounded-lg border bg-white"><table className="w-full text-left text-sm"><thead className="bg-[#F7F8FA] text-[11px] uppercase text-slate-500"><tr><th className="px-4 py-3">Dependency</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Detail</th><th className="px-4 py-3">Latency</th></tr></thead><tbody className="divide-y">{health.dependencies.map((item) => <tr key={item.name}><td className="px-4 py-3 font-semibold">{item.name}</td><td className="px-4 py-3 text-xs text-slate-500">{item.category}</td><td className="px-4 py-3"><StatusBadge value={item.status} /></td><td className="px-4 py-3 text-xs text-slate-600">{item.detail}</td><td className="px-4 py-3 text-xs">{item.latencyMs == null ? '—' : `${item.latencyMs} ms`}</td></tr>)}</tbody></table></section></>}</div>;
}
function State({ text }: { text: string }) { return <p className="mt-6 rounded-lg border bg-white p-14 text-center text-sm text-slate-500">{text}</p>; }
