import { gql, useMutation, useQuery } from '@apollo/client';
import { FormEvent, useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useAuthStore } from '../store/authStore';

const THREADS = gql`query MessagingThreads($role: MessageParticipantRole) { myMessageThreads(role: $role, limit: 50) { edges { id status lastMessage lastMessageAt unreadCount buyer { id firebaseUid name avatarUrl } seller { id firebaseUid name avatarUrl } listing { id title imageUrls status } } } unreadMessageCount }`;
const THREAD = gql`query MessagingThread($id: ID!) { messageThread(id: $id) { id status buyer { id firebaseUid name avatarUrl } seller { id firebaseUid name avatarUrl } listing { id title imageUrls status price currency } messages(limit: 100) { edges { id type body readAt createdAt sender { id firebaseUid name avatarUrl } } } } }`;
const SEND = gql`mutation SendThreadMessage($id: ID!, $body: String!) { sendMessage(threadId: $id, body: $body) { id } }`;
const READ = gql`mutation ReadThread($id: ID!) { markThreadRead(threadId: $id) }`;
const ARCHIVE = gql`mutation ArchiveMessageThread($id: ID!) { archiveThread(threadId: $id) { id status } }`;

interface Person { id: string; firebaseUid: string; name: string; avatarUrl?: string | null }
interface ThreadItem { id: string; status: string; lastMessage?: string | null; lastMessageAt?: string | null; unreadCount: number; buyer: Person; seller: Person; listing: { id: string; title: string; imageUrls: string[]; status: string } }
interface ThreadDetail { id: string; status: string; buyer: Person; seller: Person; listing: { id: string; title: string; imageUrls: string[]; status: string; price: number; currency: string }; messages: { edges: Array<{ id: string; type: string; body: string; readAt?: string | null; createdAt: string; sender: Person }> } }

export default function MessagingPage({ sellerMode = false }: { sellerMode?: boolean }) {
  const { threadId } = useParams(); const navigate = useNavigate(); const user = useAuthStore((state) => state.user); const base = sellerMode ? '/org/messages' : '/dashboard/messages';
  const [search, setSearch] = useState(''); const [body, setBody] = useState('');
  const { data, loading, error, refetch } = useQuery<{ myMessageThreads: { edges: ThreadItem[] }; unreadMessageCount: number }>(THREADS, { variables: { role: sellerMode ? 'SELLER' : null }, pollInterval: 15000 });
  const { data: detailData, refetch: refetchThread } = useQuery<{ messageThread: ThreadDetail | null }>(THREAD, { variables: { id: threadId }, skip: !threadId, pollInterval: 5000 });
  const [send, { loading: sending }] = useMutation(SEND); const [markRead] = useMutation(READ); const [archive] = useMutation(ARCHIVE);
  const threads = (data?.myMessageThreads.edges ?? []).filter((thread) => thread.listing.title.toLowerCase().includes(search.toLowerCase()) || thread.buyer.name.toLowerCase().includes(search.toLowerCase()) || thread.seller.name.toLowerCase().includes(search.toLowerCase()));
  const thread = detailData?.messageThread;
  useEffect(() => { if (!threadId) return; markRead({ variables: { id: threadId } }).then(() => refetch()); }, [threadId, markRead, refetch]);
  async function submit(event: FormEvent) { event.preventDefault(); const value = body.trim(); if (!value || !threadId) return; await send({ variables: { id: threadId, body: value } }); setBody(''); await Promise.all([refetchThread(), refetch()]); }
  async function archiveCurrent() { if (!threadId) return; await archive({ variables: { id: threadId } }); await refetchThread(); }

  return <div className={`${sellerMode ? 'h-[calc(100vh-40px)]' : 'mx-auto mb-8 mt-28 h-[75vh] max-w-7xl'} flex overflow-hidden rounded-xl border border-gray-200 bg-white`}>
    <aside className={`${threadId ? 'hidden md:flex' : 'flex'} w-full flex-col border-r border-gray-200 md:w-80 lg:w-96`}><div className="border-b p-5"><div className="flex items-center justify-between"><h1 className="font-serif text-2xl font-bold">Messages</h1>{(data?.unreadMessageCount ?? 0) > 0 && <span className="rounded-full bg-[#4a1746] px-2 py-1 text-xs text-white">{data?.unreadMessageCount}</span>}</div><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search conversations" className="mt-4 w-full rounded-full bg-[#f2edf2] px-4 py-2.5 text-sm outline-none"/></div>
      <div className="flex-1 overflow-y-auto">{loading && <p className="p-8 text-center text-sm text-gray-400">Loading...</p>}{error && <p className="p-6 text-sm text-red-600">We couldn’t load your conversations. Please try again.</p>}{!loading && threads.length === 0 && <p className="p-10 text-center text-sm text-gray-400">No conversations yet.</p>}{threads.map((item) => { const other = sellerMode ? item.buyer : item.seller; return <button key={item.id} onClick={() => navigate(`${base}/${item.id}`)} className={`flex w-full gap-3 border-b p-4 text-left hover:bg-gray-50 ${item.id === threadId ? 'bg-[#faf6ed]' : ''}`}><Avatar person={other}/><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><strong className="truncate text-sm">{other.name}</strong><time className="shrink-0 text-[10px] text-gray-400">{item.lastMessageAt ? new Date(item.lastMessageAt).toLocaleDateString() : ''}</time></div><p className="mt-1 truncate text-xs font-medium text-gray-600">{item.listing.title}</p><p className="mt-1 truncate text-xs text-gray-400">{item.lastMessage}</p></div>{item.unreadCount > 0 && <span className="mt-5 h-2 w-2 rounded-full bg-[#4a1746]"/>}</button>; })}</div></aside>
    <section className={`${threadId ? 'flex' : 'hidden md:flex'} min-w-0 flex-1 flex-col`}>{!thread ? <div className="flex flex-1 items-center justify-center text-sm text-gray-400">Select a conversation</div> : <><header className="flex items-center gap-3 border-b px-5 py-4"><button onClick={() => navigate(base)} className="md:hidden">←</button><Avatar person={sellerMode ? thread.buyer : thread.seller}/><div className="min-w-0 flex-1"><strong>{(sellerMode ? thread.buyer : thread.seller).name}</strong><Link to={`/marketplace/${thread.listing.id}`} className="block truncate text-xs text-gray-500 hover:underline">{thread.listing.title} · {thread.listing.status}</Link></div><button onClick={archiveCurrent} className="text-xs text-gray-500">Archive</button></header>
      <div className="flex-1 space-y-3 overflow-y-auto bg-[#fbfaf8] p-5">{thread.messages.edges.map((message) => { const mine = message.sender.firebaseUid === user?.uid; return <div key={message.id} className={`flex ${mine ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[78%] rounded-2xl px-4 py-3 text-sm ${mine ? 'rounded-br-sm bg-[#4a1746] text-white' : 'rounded-bl-sm border bg-white text-gray-800'}`}><p className="whitespace-pre-wrap break-words">{message.body}</p><p className={`mt-1 text-[9px] ${mine ? 'text-white/60' : 'text-gray-400'}`}>{new Date(message.createdAt).toLocaleString()}</p></div></div>; })}</div>
      <form onSubmit={submit} className="flex gap-3 border-t p-4"><textarea value={body} onChange={(event) => setBody(event.target.value)} disabled={thread.status !== 'ACTIVE'} rows={2} maxLength={2000} placeholder={thread.status === 'ACTIVE' ? 'Write a message...' : 'This conversation is archived'} className="min-w-0 flex-1 resize-none rounded-xl bg-[#f2edf2] px-4 py-3 text-sm outline-none"/><button disabled={sending || !body.trim() || thread.status !== 'ACTIVE'} className="rounded-xl bg-[#292929] px-5 text-sm font-semibold text-white disabled:opacity-40">Send</button></form></>}</section>
  </div>;
}
function Avatar({ person }: { person: Person }) { return <div className="flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden rounded-full bg-[#e9dfd2] font-serif font-bold">{person.avatarUrl ? <img src={person.avatarUrl} alt="" className="h-full w-full object-cover"/> : person.name.charAt(0)}</div>; }
