import { gql, useMutation, useQuery } from '@apollo/client';
import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { formatDate, label } from '../pages/moderation/ModerationQueuePage';

const QUERY = gql`query AdminNotificationCentre { adminNotificationUnreadCount adminNotifications(limit: 20) { id type title message href readAt createdAt } }`;
const READ = gql`mutation ReadAdminNotification($id: ID!) { markAdminNotificationRead(id: $id) { id readAt } }`;
const READ_ALL = gql`mutation ReadAllAdminNotifications { markAllAdminNotificationsRead }`;

export default function AdminNotifications() {
  const [open, setOpen] = useState(false); const root = useRef<HTMLDivElement>(null); const { data, refetch } = useQuery(QUERY, { pollInterval: 30_000 }); const [read] = useMutation(READ); const [readAll] = useMutation(READ_ALL); const count = data?.adminNotificationUnreadCount ?? 0;
  useEffect(() => { function close(event: MouseEvent) { if (!root.current?.contains(event.target as Node)) setOpen(false); } function escape(event: KeyboardEvent) { if (event.key === 'Escape') setOpen(false); } document.addEventListener('mousedown', close); document.addEventListener('keydown', escape); return () => { document.removeEventListener('mousedown', close); document.removeEventListener('keydown', escape); }; }, []);
  async function openItem(id: string) { await read({ variables: { id } }); setOpen(false); await refetch(); }
  return <div ref={root} className="relative"><button type="button" onClick={() => setOpen(!open)} aria-label={`Admin notifications, ${count} unread`} className="relative grid h-8 w-8 place-items-center rounded hover:bg-slate-100"><svg viewBox="0 0 24 24" className="h-5 w-5 fill-none stroke-current" strokeWidth="1.8"><path d="M18 9a6 6 0 10-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4" /></svg>{count > 0 && <span className="absolute -right-1 -top-1 min-w-4 rounded-full bg-red-600 px-1 text-center text-[10px] font-bold text-white">{Math.min(count, 99)}</span>}</button>{open && <div className="absolute right-0 top-10 z-50 w-[min(380px,calc(100vw-2rem))] overflow-hidden rounded-lg border bg-white shadow-xl"><div className="flex items-center justify-between border-b p-3"><div><p className="text-sm font-semibold">Notifications</p><p className="text-xs text-slate-500">{count} unread</p></div>{count > 0 && <button onClick={() => void readAll().then(() => refetch())} className="text-xs font-semibold text-blue-700">Mark all read</button>}</div><div className="max-h-[420px] overflow-y-auto">{data?.adminNotifications.length ? data.adminNotifications.map((item: { id: string; type: string; title: string; message: string; href: string | null; readAt: string | null; createdAt: string }) => <Link key={item.id} to={item.href ?? '#'} onClick={() => void openItem(item.id)} className={`block border-b p-3 hover:bg-slate-50 ${item.readAt ? '' : 'bg-blue-50/50'}`}><div className="flex justify-between gap-2"><p className="text-sm font-semibold">{item.title}</p><span className="text-[10px] font-semibold uppercase text-slate-500">{label(item.type)}</span></div><p className="mt-1 text-xs leading-5 text-slate-600">{item.message}</p><p className="mt-1 text-[10px] text-slate-400">{formatDate(item.createdAt)}</p></Link>) : <p className="p-8 text-center text-sm text-slate-500">No admin notifications.</p>}</div></div>}</div>;
}
