import { gql, useMutation, useQuery } from '@apollo/client';
import { useState, type FormEvent } from 'react';
import { formatDate, label, StatusBadge } from '../moderation/ModerationQueuePage';
import { useAdminAuth } from '../../auth/authStore';

const QUERY = gql`query AdminTemplates($type: AdminTemplateType) { adminTemplates(type: $type) { id key type title publicMessage internalGuidance locale version active createdByFirebaseUid createdAt } }`;
const CREATE = gql`mutation CreateAdminTemplate($key: String!, $type: AdminTemplateType!, $title: String!, $publicMessage: String!, $internalGuidance: String, $locale: String) { createAdminTemplate(key: $key, type: $type, title: $title, publicMessage: $publicMessage, internalGuidance: $internalGuidance, locale: $locale) { id key version active } }`;
const ACTIVATE = gql`mutation ActivateAdminTemplate($id: ID!) { activateAdminTemplate(id: $id) { id active } }`;
type Template = { id: string; key: string; type: string; title: string; publicMessage: string; internalGuidance: string | null; locale: string; version: number; active: boolean; createdByFirebaseUid: string; createdAt: string };
const empty = { key: '', type: 'WARNING', title: '', publicMessage: '', internalGuidance: '', locale: 'en' };

export default function TemplatesPage() {
  const [type, setType] = useState(''); const [form, setForm] = useState(empty); const [open, setOpen] = useState(false); const [message, setMessage] = useState('');
  const admin = useAdminAuth((state) => state.admin); const canEdit = Boolean(admin?.roles.some((role) => role !== 'AUDITOR' && role !== 'ANALYST'));
  const { data, loading, error, refetch } = useQuery<{ adminTemplates: Template[] }>(QUERY, { variables: { type: type || null } }); const [create, createState] = useMutation(CREATE); const [activate] = useMutation(ACTIVATE); const templates = data?.adminTemplates ?? [];
  async function submit(event: FormEvent) { event.preventDefault(); try { setMessage(''); await create({ variables: { ...form, internalGuidance: form.internalGuidance || null } }); setOpen(false); setForm(empty); await refetch(); } catch (value) { setMessage(value instanceof Error ? value.message : 'Template could not be saved.'); } }
  function newVersion(item: Template) { setForm({ key: item.key, type: item.type, title: item.title, publicMessage: item.publicMessage, internalGuidance: item.internalGuidance ?? '', locale: item.locale }); setOpen(true); }
  return <div className="mx-auto max-w-[1440px]"><div className="flex flex-wrap items-end justify-between gap-3 border-b pb-5"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-slate-500">Operational consistency</p><h2 className="mt-1 text-2xl font-semibold">Reason and message templates</h2><p className="mt-1 text-sm text-slate-600">Versioned public language and staff-only guidance for consistent decisions.</p></div>{canEdit && <button onClick={() => { setForm(empty); setOpen(true); }} className="h-9 rounded bg-[#0C66E4] px-4 text-sm font-semibold text-white">New template</button>}</div>
  {message && <p className="mt-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">{message}</p>}<div className="mt-5"><select value={type} onChange={(event) => setType(event.target.value)} className="h-9 rounded border bg-white px-3 text-sm"><option value="">All template types</option>{['WARNING','REJECTION','REMOVAL','SUSPENSION','VERIFICATION'].map((value) => <option key={value}>{value}</option>)}</select></div>
  <section className="mt-4 overflow-hidden rounded-lg border bg-white">{loading ? <State text="Loading templates…" /> : error ? <State text={error.message} /> : !templates.length ? <State text="No templates match this view." /> : <div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-[#F7F8FA] text-[11px] uppercase text-slate-500"><tr><th className="px-4 py-3">Template</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Version</th><th className="px-4 py-3">Public message</th><th className="px-4 py-3">Created</th><th className="px-4 py-3">Actions</th></tr></thead><tbody className="divide-y">{templates.map((item) => <tr key={item.id} className="align-top"><td className="px-4 py-3"><p className="font-semibold">{item.title}</p><p className="text-xs text-slate-500">{item.key} · {item.locale}</p></td><td className="px-4 py-3">{label(item.type)}</td><td className="px-4 py-3"><p className="font-semibold">v{item.version}</p><StatusBadge value={item.active ? 'ACTIVE' : 'INACTIVE'} /></td><td className="max-w-lg px-4 py-3 text-xs leading-5 text-slate-600">{item.publicMessage}<details className="mt-2"><summary className="cursor-pointer font-semibold text-blue-700">Internal guidance</summary><p className="mt-1">{item.internalGuidance ?? 'No internal guidance.'}</p></details></td><td className="px-4 py-3 text-xs">{formatDate(item.createdAt)}<p className="mt-1 text-slate-500">{item.createdByFirebaseUid}</p></td><td className="px-4 py-3"><div className="grid gap-2 text-left"><button onClick={() => newVersion(item)} className="text-xs font-semibold text-blue-700">Create new version</button>{!item.active && <button onClick={() => void activate({ variables: { id: item.id } }).then(() => refetch())} className="text-xs font-semibold text-green-700">Activate version</button>}</div></td></tr>)}</tbody></table></div>}</section>
  {open && <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/40 p-4"><form onSubmit={submit} role="dialog" aria-modal="true" className="my-8 w-full max-w-2xl rounded-lg bg-white p-6"><h3 className="text-lg font-semibold">{templates.some((item) => item.key === form.key) ? 'Create template version' : 'Create template'}</h3><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Stable key"><input required value={form.key} onChange={(event) => setForm({ ...form, key: event.target.value })} disabled={templates.some((item) => item.key === form.key)} className="control" /></Field><Field label="Type"><select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })} className="control">{['WARNING','REJECTION','REMOVAL','SUSPENSION','VERIFICATION'].map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="Title"><input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} className="control" /></Field><Field label="Locale"><input required value={form.locale} onChange={(event) => setForm({ ...form, locale: event.target.value })} className="control" /></Field></div><Field label="Public message"><textarea required minLength={5} maxLength={2000} rows={5} value={form.publicMessage} onChange={(event) => setForm({ ...form, publicMessage: event.target.value })} className="control" /></Field><Field label="Internal guidance"><textarea maxLength={2000} rows={4} value={form.internalGuidance} onChange={(event) => setForm({ ...form, internalGuidance: event.target.value })} className="control" /></Field><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="h-9 rounded border px-4 text-sm font-semibold">Cancel</button><button disabled={createState.loading} className="h-9 rounded bg-[#0C66E4] px-4 text-sm font-semibold text-white disabled:opacity-50">Save active version</button></div></form></div>}</div>;
}
function Field({ label: text, children }: { label: string; children: React.ReactNode }) { return <label className="mt-4 block text-sm font-semibold text-slate-700">{text}{children}</label>; }
function State({ text }: { text: string }) { return <p className="p-14 text-center text-sm text-slate-500">{text}</p>; }
