import { gql, useMutation, useQuery } from '@apollo/client';
import { useState, type FormEvent } from 'react';
import { firebaseAuth } from '../../firebase';
import { AdminPagination, useAdminTableState, useClampAdminPage } from '../../components/AdminTableControls';

const FIELDS = `id releaseKey title summary body audiences status imageUrl imageAlt videoUrl buttonLabel buttonUrl publishAt publishedAt archivedAt createdAt updatedAt`;
const QUERY = gql(`query ProductAnnouncementAdminPage($status: AnnouncementStatus, $audience: AnnouncementAudience, $search: String, $limit: Int, $offset: Int, $sortBy: String, $sortDirection: AdminSortDirection) { productAnnouncementPage(status: $status, audience: $audience, search: $search, limit: $limit, offset: $offset, sortBy: $sortBy, sortDirection: $sortDirection) { edges { ${FIELDS} } totalCount } }`);
const CREATE = gql(`mutation CreateProductAnnouncement($input: ProductAnnouncementInput!) { createProductAnnouncement(input: $input) { ${FIELDS} } }`);
const UPDATE = gql(`mutation UpdateProductAnnouncement($id: ID!, $input: ProductAnnouncementInput!) { updateProductAnnouncement(id: $id, input: $input) { ${FIELDS} } }`);
const PUBLISH = gql(`mutation PublishProductAnnouncement($id: ID!, $publishAt: DateTime) { publishProductAnnouncement(id: $id, publishAt: $publishAt) { ${FIELDS} } }`);
const ARCHIVE = gql(`mutation ArchiveProductAnnouncement($id: ID!) { archiveProductAnnouncement(id: $id) { ${FIELDS} } }`);

type Announcement = { id: string; releaseKey: string; title: string; summary: string | null; body: string; audiences: string[]; status: string; imageUrl: string | null; imageAlt: string | null; videoUrl: string | null; buttonLabel: string | null; buttonUrl: string | null; publishAt: string | null; publishedAt: string | null; archivedAt: string | null; createdAt: string; updatedAt: string };
type Form = Omit<Announcement, 'id' | 'status' | 'publishAt' | 'publishedAt' | 'archivedAt' | 'createdAt' | 'updatedAt'>;
const empty: Form = { releaseKey: '', title: '', summary: '', body: '', audiences: ['MEMBER', 'ORGANISATION'], imageUrl: '', imageAlt: '', videoUrl: '', buttonLabel: '', buttonUrl: '' };

export default function AnnouncementsPage() {
  const table = useAdminTableState('updatedAt', 'DESC'); const status = table.get('status'); const audience = table.get('audience');
  const [search, setSearch] = useState(table.search); const [form, setForm] = useState<Form>(empty); const [editing, setEditing] = useState<string | null>(null); const [preview, setPreview] = useState<Announcement | Form | null>(null); const [publishAt, setPublishAt] = useState(''); const [message, setMessage] = useState('');
  const { data, loading, error, refetch } = useQuery<{ productAnnouncementPage: { edges: Announcement[]; totalCount: number } }>(QUERY, { variables: { status: status || null, audience: audience || null, search: table.search || null, limit: table.pageSize, offset: table.offset, sortBy: table.sortBy, sortDirection: table.sortDirection } });
  const [create, createState] = useMutation(CREATE); const [update, updateState] = useMutation(UPDATE); const [publish] = useMutation(PUBLISH); const [archive] = useMutation(ARCHIVE);
  const rows = data?.productAnnouncementPage.edges ?? []; useClampAdminPage(data?.productAnnouncementPage.totalCount, table.page, table.pageSize, table.setPage);
  const input = () => ({ ...form, summary: form.summary || null, imageUrl: form.imageUrl || null, imageAlt: form.imageAlt || null, videoUrl: form.videoUrl || null, buttonLabel: form.buttonLabel || null, buttonUrl: form.buttonUrl || null });
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(''); try { if (editing) await update({ variables: { id: editing, input: input() } }); else await create({ variables: { input: input() } }); setForm(empty); setEditing(null); setMessage('Draft saved.'); await refetch(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Announcement could not be saved.'); } }
  function edit(item: Announcement) { setEditing(item.id); setForm({ releaseKey: item.releaseKey, title: item.title, summary: item.summary ?? '', body: item.body, audiences: item.audiences, imageUrl: item.imageUrl ?? '', imageAlt: item.imageAlt ?? '', videoUrl: item.videoUrl ?? '', buttonLabel: item.buttonLabel ?? '', buttonUrl: item.buttonUrl ?? '' }); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  async function upload(file: File, kind: 'image' | 'video') { setMessage(`Uploading ${kind}…`); try { const token = await firebaseAuth.currentUser?.getIdToken(); if (!token) throw new Error('Sign in before uploading.'); const endpoint = process.env['CL_ADMIN_MEDIA_URL'] ?? 'http://localhost:4004/media/upload'; const response = await fetch(`${endpoint}?purpose=${kind === 'image' ? 'ANNOUNCEMENT_IMAGE' : 'ANNOUNCEMENT_VIDEO'}`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/octet-stream', 'X-File-Name': file.name, 'X-File-Type': file.type }, body: file }); const result = await response.json() as { url?: string; error?: string }; if (!response.ok || !result.url) throw new Error(result.error ?? 'Upload failed.'); setForm((current) => ({ ...current, [kind === 'image' ? 'imageUrl' : 'videoUrl']: result.url as string })); setMessage(`${kind === 'image' ? 'Image' : 'Video'} uploaded.`); } catch (e) { setMessage(e instanceof Error ? e.message : 'Upload failed.'); } }
  async function changeStatus(action: 'publish' | 'archive', item: Announcement) { try { if (action === 'publish') await publish({ variables: { id: item.id, publishAt: publishAt ? new Date(publishAt).toISOString() : null } }); else await archive({ variables: { id: item.id } }); setPublishAt(''); await refetch(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Status could not be changed.'); } }
  return <div className="space-y-6">
    <div><h2 className="text-2xl font-semibold">What’s New</h2><p className="mt-1 text-sm text-slate-500">Create release announcements and control who sees them.</p></div>
    <form onSubmit={submit} className="rounded-lg border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h3 className="font-semibold">{editing ? 'Edit announcement' : 'New announcement draft'}</h3><button type="button" onClick={() => setPreview(form)} className="rounded border px-3 py-1.5 text-xs font-semibold">Preview</button></div>
      <div className="grid gap-4 md:grid-cols-2"><Field label="Release key"><input required value={form.releaseKey} onChange={(e) => setForm({ ...form, releaseKey: e.target.value })} placeholder="2026.08-community-updates" className={control} /></Field><Field label="Title"><input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className={control} /></Field></div>
      <Field label="Short summary"><input value={form.summary ?? ''} maxLength={240} onChange={(e) => setForm({ ...form, summary: e.target.value })} className={control} /></Field>
      <Field label="Content"><textarea required rows={7} value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} className={control} placeholder={'Use blank lines for paragraphs and lines beginning with • or - for lists.'} /></Field>
      <Field label="Audience"><div className="flex flex-wrap gap-4">{['MEMBER', 'ORGANISATION', 'ADMIN'].map((value) => <label key={value} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.audiences.includes(value)} onChange={(e) => setForm({ ...form, audiences: e.target.checked ? [...form.audiences, value] : form.audiences.filter((item) => item !== value) })} />{value === 'ORGANISATION' ? 'Organisation users' : value[0] + value.slice(1).toLowerCase() + 's'}</label>)}</div></Field>
      <div className="grid gap-4 md:grid-cols-2"><Field label="Image"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => e.target.files?.[0] && void upload(e.target.files[0], 'image')} className={control} /><input value={form.imageAlt ?? ''} onChange={(e) => setForm({ ...form, imageAlt: e.target.value })} placeholder="Image description" className={`${control} mt-2`} /></Field><Field label="Video (max 20 MB)"><input type="file" accept="video/mp4,video/quicktime,video/webm" onChange={(e) => e.target.files?.[0] && void upload(e.target.files[0], 'video')} className={control} /></Field></div>
      <div className="grid gap-4 md:grid-cols-2"><Field label="Button label"><input value={form.buttonLabel ?? ''} onChange={(e) => setForm({ ...form, buttonLabel: e.target.value })} className={control} /></Field><Field label="Button destination"><input value={form.buttonUrl ?? ''} onChange={(e) => setForm({ ...form, buttonUrl: e.target.value })} placeholder="/events or https://…" className={control} /></Field></div>
      {message && <p className="mt-3 text-sm text-slate-600">{message}</p>}<div className="mt-4 flex gap-2"><button disabled={createState.loading || updateState.loading} className="rounded bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Save draft</button>{editing && <button type="button" onClick={() => { setEditing(null); setForm(empty); }} className="rounded border px-4 py-2 text-sm">Cancel edit</button>}</div>
    </form>
    <section className="rounded-lg border bg-white"><div className="flex flex-wrap gap-2 border-b p-4"><form onSubmit={(e) => { e.preventDefault(); table.setSearch(search); }} className="flex gap-2"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search announcements" className={control} /><button className="rounded bg-slate-800 px-3 text-sm text-white">Search</button></form><select value={status} onChange={(e) => table.update({ status: e.target.value })} className={control}><option value="">All statuses</option>{['DRAFT','SCHEDULED','PUBLISHED','ARCHIVED'].map((v) => <option key={v}>{v}</option>)}</select><select value={audience} onChange={(e) => table.update({ audience: e.target.value })} className={control}><option value="">All audiences</option>{['MEMBER','ORGANISATION','ADMIN'].map((v) => <option key={v}>{v}</option>)}</select></div>
      {loading ? <p className="p-8 text-center text-sm">Loading…</p> : error ? <p className="p-8 text-center text-sm text-red-600">Announcements could not be loaded.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Release</th><th className="p-3">Audience</th><th className="p-3">Status</th><th className="p-3">Publish</th><th className="p-3">Actions</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id} className="border-t"><td className="p-3"><p className="font-semibold">{item.title}</p><p className="text-xs text-slate-500">{item.releaseKey}</p></td><td className="p-3 text-xs">{item.audiences.join(', ')}</td><td className="p-3"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">{item.status}</span></td><td className="p-3 text-xs">{item.publishAt ? new Date(item.publishAt).toLocaleString() : 'Not set'}</td><td className="p-3"><div className="flex flex-wrap gap-2"><button onClick={() => setPreview(item)} className="text-blue-700">Preview</button>{item.status !== 'ARCHIVED' && <button onClick={() => edit(item)} className="text-blue-700">Edit</button>}{['DRAFT','SCHEDULED'].includes(item.status) && <button onClick={() => void changeStatus('publish', item)} className="text-emerald-700">Publish</button>}{item.status !== 'ARCHIVED' && <button onClick={() => void changeStatus('archive', item)} className="text-red-700">Archive</button>}</div></td></tr>)}</tbody></table></div>}
      <div className="border-t p-3"><AdminPagination page={table.page} pageSize={table.pageSize} totalCount={data?.productAnnouncementPage.totalCount ?? 0} onPageChange={table.setPage} onPageSizeChange={table.setPageSize} /></div>
    </section>
    {rows.some((item) => ['DRAFT','SCHEDULED'].includes(item.status)) && <div className="rounded-lg border bg-white p-4"><label className="text-sm font-semibold">Optional schedule time</label><input type="datetime-local" value={publishAt} onChange={(e) => setPublishAt(e.target.value)} className={`${control} mt-2 max-w-xs`} /><p className="mt-1 text-xs text-slate-500">When set, the next Publish action schedules that release. Leave empty to publish now.</p></div>}
    {preview && <Preview item={preview} close={() => setPreview(null)} />}
  </div>;
}

const control = 'rounded border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-blue-500';
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="mt-4 block"><span className="mb-1.5 block text-xs font-semibold uppercase tracking-wide text-slate-600">{label}</span>{children}</label>; }
function Preview({ item, close }: { item: Announcement | Form; close: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4" onMouseDown={close}><article onMouseDown={(e) => e.stopPropagation()} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-xl bg-white shadow-2xl">{item.imageUrl && <img src={item.imageUrl} alt={item.imageAlt ?? ''} className="h-60 w-full object-cover" />}<div className="p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-700">What’s New</p><h2 className="mt-2 text-2xl font-semibold">{item.title || 'Announcement title'}</h2></div><button onClick={close} aria-label="Close preview" className="text-2xl">×</button></div>{item.summary && <p className="mt-3 text-slate-600">{item.summary}</p>}<div className="mt-5 whitespace-pre-wrap text-sm leading-7 text-slate-700">{item.body || 'Announcement content appears here.'}</div>{item.videoUrl && <video src={item.videoUrl} controls className="mt-5 w-full rounded-lg" />}{item.buttonLabel && item.buttonUrl && <a href={item.buttonUrl} className="mt-6 inline-block rounded bg-blue-600 px-4 py-2 text-sm font-semibold text-white">{item.buttonLabel}</a>}</div></article></div>; }
