import { gql, useMutation, useQuery } from '@apollo/client';
import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useAdminAuth } from '../../auth/authStore';
import { formatDate, label, StatusBadge } from '../moderation/ModerationQueuePage';

const QUERY = gql`query AdminVerification($id: ID!) { verificationSubmission(id: $id) { id organisationId organisationName ownerFirebaseUid version status requestedTier approvedTier documentLabels officialName registrationNumber officialEmail pocName pocTitle organisationType region assigneeFirebaseUid decisionReason reviewedByFirebaseUid reviewedAt dueAt createdAt history { id version status createdAt reviewedAt decisionReason } auditTimeline { id adminFirebaseUid action reason createdAt } } }`;
const ASSIGN = gql`mutation AssignVerification($id: ID!, $assigneeFirebaseUid: String) { assignVerificationSubmission(id: $id, assigneeFirebaseUid: $assigneeFirebaseUid) { id assigneeFirebaseUid } }`;
const ACCESS = gql`mutation AccessVerificationDocument($id: ID!, $documentIndex: Int!) { accessVerificationDocument(id: $id, documentIndex: $documentIndex) }`;
const DECIDE = gql`mutation DecideVerification($id: ID!, $action: VerificationDecision!, $tier: VerificationTier, $reason: String!) { decideVerificationSubmission(id: $id, action: $action, tier: $tier, reason: $reason) { id status approvedTier decisionReason reviewedAt } }`;
type Item = { id: string; organisationId: string; organisationName: string; ownerFirebaseUid: string; version: number; status: string; requestedTier: string; approvedTier: string | null; documentLabels: string[]; officialName: string | null; registrationNumber: string | null; officialEmail: string | null; pocName: string | null; pocTitle: string | null; organisationType: string | null; region: string | null; assigneeFirebaseUid: string | null; decisionReason: string | null; reviewedByFirebaseUid: string | null; reviewedAt: string | null; dueAt: string; createdAt: string; history: Array<{ id: string; version: number; status: string; createdAt: string; reviewedAt: string | null; decisionReason: string | null }>; auditTimeline: Array<{ id: string; adminFirebaseUid: string; action: string; reason: string; createdAt: string }> };

export default function VerificationCasePage() {
  const { verificationId = '' } = useParams(); const admin = useAdminAuth((state) => state.admin); const [decision, setDecision] = useState<'APPROVE' | 'REJECT' | 'NEEDS_INFORMATION' | null>(null); const [tier, setTier] = useState('STANDARD'); const [reason, setReason] = useState(''); const [message, setMessage] = useState('');
  const { data, loading, error, refetch } = useQuery<{ verificationSubmission: Item | null }>(QUERY, { variables: { id: verificationId } }); const [assign] = useMutation(ASSIGN); const [access] = useMutation(ACCESS); const [decide, { loading: deciding }] = useMutation(DECIDE); const item = data?.verificationSubmission; const canReview = Boolean(admin?.roles.some((role) => role === 'SUPER_ADMIN' || role === 'VERIFICATION_REVIEWER'));
  if (loading) return <State text="Loading submission…" />; if (error || !item) return <State text={error?.message ?? 'Submission not found'} />;
  async function openDocument(index: number) { try { const result = await access({ variables: { id: item?.id, documentIndex: index } }); const url = result.data?.accessVerificationDocument as string | undefined; if (url) window.open(url, '_blank', 'noopener,noreferrer'); } catch (value) { setMessage(errorText(value)); } }
  async function submitDecision() { if (!item || !decision) return; try { setMessage(''); await decide({ variables: { id: item.id, action: decision, tier: decision === 'APPROVE' ? tier : null, reason } }); setDecision(null); setReason(''); await refetch(); } catch (value) { setMessage(errorText(value)); } }
  return <div className="mx-auto max-w-[1440px]"><div className="border-b border-[#DFE1E6] pb-5"><Link to="/verifications" className="text-xs font-semibold text-blue-700">← Verification queue</Link><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><div className="flex items-center gap-2"><StatusBadge value={item.status} /><span className="text-xs text-slate-500">Submission v{item.version}</span></div><h2 className="mt-2 text-2xl font-semibold">{item.organisationName}</h2><p className="text-sm text-slate-600">{item.organisationId}</p></div>{canReview && item.status === 'PENDING_REVIEW' && <button onClick={() => void assign({ variables: { id: item.id, assigneeFirebaseUid: item.assigneeFirebaseUid ? null : admin?.firebaseUid } }).then(() => refetch())} className="h-9 rounded border bg-white px-3 text-sm font-semibold">{item.assigneeFirebaseUid ? 'Unassign' : 'Assign to me'}</button>}</div></div>{message && <p role="alert" className="mt-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">{message}</p>}
  <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_340px]"><div className="space-y-6"><Card title="Submitted identity"><dl className="grid gap-px bg-[#DFE1E6] sm:grid-cols-2"><Fact name="Official name" value={item.officialName} /><Fact name="Registration number" value={item.registrationNumber} /><Fact name="Official email" value={item.officialEmail} /><Fact name="Point of contact" value={[item.pocName, item.pocTitle].filter(Boolean).join(', ')} /><Fact name="Organisation type" value={item.organisationType} /><Fact name="Region" value={item.region} /></dl></Card><Card title="Documents"><div className="divide-y">{item.documentLabels.map((name, index) => <div key={`${name}-${index}`} className="flex items-center justify-between gap-3 p-4"><span className="text-sm font-medium">{name}</span>{canReview ? <button onClick={() => void openDocument(index)} className="text-sm font-semibold text-blue-700">Open securely</button> : <span className="text-xs text-slate-500">Reviewer access required</span>}</div>)}</div></Card><Card title="Submission history"><div className="divide-y">{item.history.map((entry) => <div key={entry.id} className="p-4"><div className="flex justify-between"><span className="text-sm font-semibold">Version {entry.version} · {label(entry.status)}</span><span className="text-xs text-slate-500">{formatDate(entry.createdAt)}</span></div>{entry.decisionReason && <p className="mt-2 text-sm text-slate-600">{entry.decisionReason}</p>}</div>)}</div></Card><Card title="Audit timeline"><div className="divide-y">{item.auditTimeline.map((entry) => <div key={entry.id} className="p-4"><p className="text-sm font-semibold">{label(entry.action)}</p><p className="mt-1 text-xs text-slate-500">{entry.adminFirebaseUid} · {formatDate(entry.createdAt)}</p><p className="mt-2 text-sm">{entry.reason}</p></div>)}</div></Card></div>
  <aside className="space-y-4"><Card title="Review context"><div className="p-4 text-sm"><p><b>Requested tier:</b> {label(item.requestedTier)}</p><p className="mt-2"><b>Assignee:</b> {item.assigneeFirebaseUid ?? 'Unassigned'}</p><p className="mt-2"><b>SLA due:</b> {formatDate(item.dueAt)}</p></div></Card>{item.status === 'PENDING_REVIEW' && canReview ? <Card title="Decision"><div className="grid gap-2 p-4"><button onClick={() => { setDecision('APPROVE'); setReason('Registration and supporting documents meet the verification requirements.'); }} className="rounded border border-green-200 p-3 text-left text-sm font-semibold text-green-800">Approve</button><button onClick={() => { setDecision('NEEDS_INFORMATION'); setReason('Please provide a clearer or current supporting registration document.'); }} className="rounded border border-amber-200 p-3 text-left text-sm font-semibold text-amber-800">Request information</button><button onClick={() => { setDecision('REJECT'); setReason('The submitted information could not be validated against the supporting documents.'); }} className="rounded border border-red-200 p-3 text-left text-sm font-semibold text-red-800">Reject</button></div></Card> : item.decisionReason && <Card title="Decision"><p className="p-4 text-sm">{item.decisionReason}</p></Card>}</aside></div>
  {decision && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div role="dialog" aria-modal="true" className="w-full max-w-lg rounded-lg bg-white p-6"><h3 className="text-lg font-semibold">{label(decision)}</h3>{decision === 'APPROVE' && <label className="mt-4 block text-sm font-semibold">Approved tier<select value={tier} onChange={(event) => setTier(event.target.value)} className="mt-2 h-10 w-full rounded border px-3"><option>STANDARD</option><option>CHARITY</option><option>NGO</option></select></label>}<label className="mt-4 block text-sm font-semibold">Reason<textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={4} className="mt-2 w-full rounded border p-3 text-sm" /></label><div className="mt-5 flex justify-end gap-2"><button onClick={() => setDecision(null)} className="h-9 rounded border px-4 text-sm font-semibold">Cancel</button><button disabled={deciding || reason.trim().length < 5} onClick={() => void submitDecision()} className="h-9 rounded bg-[#0C66E4] px-4 text-sm font-semibold text-white disabled:opacity-50">Confirm</button></div></div></div>}</div>;
}
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="overflow-hidden rounded-lg border border-[#DFE1E6] bg-white"><h3 className="border-b px-4 py-3 text-sm font-semibold">{title}</h3>{children}</section>; }
function Fact({ name, value }: { name: string; value: string | null }) { return <div className="bg-white p-4"><dt className="text-[11px] font-semibold uppercase text-slate-500">{name}</dt><dd className="mt-1 text-sm">{value || 'Not supplied'}</dd></div>; }
function State({ text }: { text: string }) { return <div className="rounded-lg border bg-white p-16 text-center text-sm text-slate-500">{text}</div>; }
function errorText(value: unknown) { return value instanceof Error ? value.message : 'Action failed.'; }
