import { gql, useMutation, useQuery } from '@apollo/client';
import { useMemo, useState, type FormEvent } from 'react';
import { formatDate, label, StatusBadge } from '../moderation/ModerationQueuePage';
import { useAdminAuth } from '../../auth/authStore';

const AUDIT = gql`query AdminAudit($targetType: ContentType, $action: AuditAction, $result: AuditResult, $from: DateTime, $to: DateTime, $after: String) { auditEvents(targetType: $targetType, action: $action, result: $result, from: $from, to: $to, limit: 50, after: $after) { edges { id adminFirebaseUid adminRoles action targetId targetType reason beforeStatus afterStatus requestId result route ipAddress userAgent createdAt } hasNextPage endCursor } auditExports { id from to status rowCount failureReason expiresAt createdAt } savedAdminViews(module: AUDIT) { id name filtersJson } }`;
const REQUEST_EXPORT = gql`mutation RequestAuditExport($from: DateTime!, $to: DateTime!) { requestAuditExport(from: $from, to: $to) { id status rowCount expiresAt } }`;
const EXPORT_CONTENT = gql`query AuditExportContent($id: ID!) { auditExportContent(id: $id) }`;
const SAVE_VIEW = gql`mutation SaveAuditView($name: String!, $filtersJson: String!) { saveAdminView(name: $name, module: AUDIT, filtersJson: $filtersJson) { id name filtersJson } }`;
const DELETE_VIEW = gql`mutation DeleteAuditView($id: ID!) { deleteSavedAdminView(id: $id) }`;
type EventRow = { id: string; adminFirebaseUid: string; adminRoles: string[]; action: string; targetId: string; targetType: string; reason: string; beforeStatus: string | null; afterStatus: string | null; requestId: string | null; result: string; route: string | null; ipAddress: string | null; userAgent: string | null; createdAt: string };
type FilterState = { targetType: string; action: string; result: string; from: string; to: string };
const initialFilters: FilterState = { targetType: '', action: '', result: '', from: '', to: '' };

export default function AuditPage() {
  const [filters, setFilters] = useState(initialFilters); const [applied, setApplied] = useState(initialFilters); const [viewName, setViewName] = useState(''); const [message, setMessage] = useState('');
  const admin = useAdminAuth((state) => state.admin); const canExport = Boolean(admin?.roles.some((role) => role === 'SUPER_ADMIN' || role === 'AUDITOR'));
  const variables = useMemo(() => ({ targetType: applied.targetType || null, action: applied.action || null, result: applied.result || null, from: applied.from ? new Date(`${applied.from}T00:00:00`).toISOString() : null, to: applied.to ? new Date(`${applied.to}T23:59:59`).toISOString() : null, after: null }), [applied]);
  const { data, loading, error, refetch, fetchMore } = useQuery(AUDIT, { variables, notifyOnNetworkStatusChange: true, pollInterval: 10_000 }); const [requestExport, exportState] = useMutation(REQUEST_EXPORT); const [saveView] = useMutation(SAVE_VIEW); const [deleteView] = useMutation(DELETE_VIEW); const events: EventRow[] = data?.auditEvents.edges ?? [];
  function apply(event: FormEvent) { event.preventDefault(); setApplied(filters); }
  async function exportCsv() { if (!applied.from || !applied.to) { setMessage('Select a bounded date range before requesting an export.'); return; } try { setMessage(''); await requestExport({ variables: { from: new Date(`${applied.from}T00:00:00`).toISOString(), to: exportEnd(applied.to) } }); setMessage('Export queued. Its status will update automatically.'); await refetch(); } catch (value) { setMessage(errorText(value)); } }
  async function download(id: string) { const result = await refetchExport(id); const csv = result; const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `cl-audit-${id}.csv`; link.click(); URL.revokeObjectURL(url); }
  async function refetchExport(id: string) { const result = await import('../../apollo/client').then(({ adminApolloClient }) => adminApolloClient.query<{ auditExportContent: string }>({ query: EXPORT_CONTENT, variables: { id }, fetchPolicy: 'network-only' })); return result.data.auditExportContent; }
  async function persistView() { if (!viewName.trim()) return; await saveView({ variables: { name: viewName.trim(), filtersJson: JSON.stringify(applied) } }); setViewName(''); await refetch(); }
  function loadView(filtersJson: string) { try { const value = JSON.parse(filtersJson) as FilterState; setFilters(value); setApplied(value); } catch { setMessage('The saved view could not be read.'); } }
  return <div className="mx-auto max-w-[1440px]"><div className="flex flex-col justify-between gap-3 border-b pb-5 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.12em] text-slate-500">Security and operations</p><h2 className="mt-1 text-2xl font-semibold">Audit log</h2><p className="mt-1 text-sm text-slate-600">Append-only privileged reads and actions with bounded, watermarked exports.</p></div>{canExport && <button disabled={exportState.loading} onClick={() => void exportCsv()} className="h-9 rounded bg-[#0C66E4] px-4 text-sm font-semibold text-white disabled:opacity-50">Request CSV export</button>}</div>
  {message && <p className="mt-4 rounded border border-blue-200 bg-blue-50 p-3 text-sm text-blue-900">{message}</p>}
  <form onSubmit={apply} className="mt-5 grid gap-3 rounded-lg border bg-white p-4 md:grid-cols-3 xl:grid-cols-6"><Select label="Target" value={filters.targetType} onChange={(value) => setFilters({ ...filters, targetType: value })} options={['MARKETPLACE_ITEM','ORGANISATION_VERIFICATION','USER','ORGANISATION','EVENT','JOB','AUDIT_EXPORT','TEMPLATE','FEATURED_PLACEMENT','SAVED_VIEW']} /><Select label="Action" value={filters.action} onChange={(value) => setFilters({ ...filters, action: value })} options={['ACCESS_DOCUMENT','ACCESS_PRIVATE_DATA','ACCOUNT_SUSPEND','ACCOUNT_REACTIVATE','VERIFICATION_APPROVE','VERIFICATION_REJECT','REQUEST_AUDIT_EXPORT','TEMPLATE_CREATE','PLACEMENT_CREATE','PLACEMENT_UPDATE']} /><Select label="Result" value={filters.result} onChange={(value) => setFilters({ ...filters, result: value })} options={['SUCCESS','FAILED']} /><DateField label="From" value={filters.from} onChange={(value) => setFilters({ ...filters, from: value })} /><DateField label="To" value={filters.to} onChange={(value) => setFilters({ ...filters, to: value })} /><button className="mt-auto h-9 rounded border bg-slate-50 px-3 text-sm font-semibold">Apply filters</button></form>
  <section className="mt-4 rounded-lg border bg-white p-4"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold uppercase text-slate-500">Saved views</span>{data?.savedAdminViews.map((view: { id: string; name: string; filtersJson: string }) => <span key={view.id} className="inline-flex items-center rounded border bg-slate-50"><button onClick={() => loadView(view.filtersJson)} className="px-2 py-1 text-xs font-semibold text-blue-700">{view.name}</button><button aria-label={`Delete ${view.name}`} onClick={() => void deleteView({ variables: { id: view.id } }).then(() => refetch())} className="border-l px-2 py-1 text-xs text-red-700">×</button></span>)}<input value={viewName} onChange={(event) => setViewName(event.target.value)} placeholder="New view name" className="ml-auto h-8 rounded border px-2 text-xs" /><button onClick={() => void persistView()} className="h-8 rounded border px-2 text-xs font-semibold">Save current</button></div></section>
  <section className="mt-4 overflow-hidden rounded-lg border bg-white">{loading && !events.length ? <State text="Loading audit history…" /> : error ? <State text={error.message} /> : !events.length ? <State text="No audit events match this view." /> : <div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-sm"><thead className="bg-[#F7F8FA] text-[11px] uppercase text-slate-500"><tr><th className="px-4 py-3">When / admin</th><th className="px-4 py-3">Action</th><th className="px-4 py-3">Target</th><th className="px-4 py-3">Reason</th><th className="px-4 py-3">Result</th><th className="px-4 py-3">Request context</th></tr></thead><tbody className="divide-y">{events.map((row) => <tr key={row.id} className="align-top hover:bg-slate-50"><td className="px-4 py-3"><p className="font-medium">{formatDate(row.createdAt)}</p><p className="mt-1 text-xs text-slate-500">{row.adminFirebaseUid}</p><p className="text-[10px] text-slate-400">{row.adminRoles.join(', ') || 'Legacy event'}</p></td><td className="px-4 py-3 font-semibold">{label(row.action)}</td><td className="px-4 py-3"><p>{label(row.targetType)}</p><p className="break-all text-xs text-slate-500">{row.targetId}</p></td><td className="max-w-md px-4 py-3 text-xs leading-5">{row.reason}{(row.beforeStatus || row.afterStatus) && <p className="mt-1 text-slate-500">{row.beforeStatus ?? '—'} → {row.afterStatus ?? '—'}</p>}</td><td className="px-4 py-3"><StatusBadge value={row.result} /></td><td className="px-4 py-3 text-xs text-slate-500"><p>{row.route ?? 'Unknown route'}</p><p>{row.requestId ?? 'No request ID'}</p><p>{row.ipAddress ?? 'IP unavailable'}</p></td></tr>)}</tbody></table></div>}{data?.auditEvents.hasNextPage && <div className="border-t p-3 text-center"><button onClick={() => void fetchMore({ variables: { ...variables, after: data.auditEvents.endCursor }, updateQuery: (previous, { fetchMoreResult }) => fetchMoreResult ? { ...previous, auditEvents: { ...fetchMoreResult.auditEvents, edges: [...previous.auditEvents.edges, ...fetchMoreResult.auditEvents.edges] } } : previous })} className="rounded border px-4 py-2 text-sm font-semibold">Load more</button></div>}</section>
  <section className="mt-6 rounded-lg border bg-white"><div className="border-b p-4"><h3 className="text-sm font-semibold">Export centre</h3><p className="mt-1 text-xs text-slate-500">Exports expire automatically after 24 hours.</p></div><div className="divide-y">{data?.auditExports.length ? data.auditExports.map((item: { id: string; from: string; to: string; status: string; rowCount: number; failureReason: string | null; expiresAt: string }) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="text-sm font-semibold">{item.rowCount} audit rows · {label(item.status)}</p><p className="text-xs text-slate-500">{formatDate(item.from)} — {formatDate(item.to)} · expires {formatDate(item.expiresAt)}</p></div>{item.status === 'READY' && <button onClick={() => void download(item.id)} className="text-sm font-semibold text-blue-700">Download</button>}</div>) : <State text="No audit exports requested." />}</div></section></div>;
}
function Select({ label: text, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="text-xs font-semibold text-slate-600">{text}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 h-9 w-full rounded border px-2 text-sm"><option value="">All</option>{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
function DateField({ label: text, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-xs font-semibold text-slate-600">{text}<input type="date" value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 h-9 w-full rounded border px-2 text-sm" /></label>; }
function State({ text }: { text: string }) { return <p className="p-10 text-center text-sm text-slate-500">{text}</p>; }
function errorText(value: unknown) { return value instanceof Error ? value.message : 'Action failed.'; }
function exportEnd(value: string) { const end = new Date(`${value}T23:59:59`); const now = new Date(); return new Date(Math.min(end.getTime(), now.getTime())).toISOString(); }
